# Generated by Shiori. Safe to run from a checkout or through irm | iex.
[CmdletBinding()]
param([string[]]$Install = @())

$Repository = if ($env:SHIORI_REPOSITORY) { $env:SHIORI_REPOSITORY } else { 'Dragonshorn-Studios/shiori-brain' }
$Marketplace = if ($env:SHIORI_MARKETPLACE) { $env:SHIORI_MARKETPLACE } else { 'dragonshorn-brain' }
$GuideUrl = "https://github.com/$Repository/blob/main/AGENT-SETUP.md"
$LocalCheckout = (Test-Path -LiteralPath '.agents\skills') -and (Test-Path -LiteralPath 'plugins\shiori')
$Mode = if ($LocalCheckout) { 'checkout' } else { 'remote' }
$ProjectHint = if ($LocalCheckout) { 'project adapters are ready in this checkout' } else { 'no Shiori checkout detected; use a marketplace installation below' }

function Show-AgentStatus {
    param([string]$Name, [string]$Command, [string]$HomePath, [switch]$Cloud)
    $Executable = Get-Command $Command -ErrorAction SilentlyContinue
    $ConfigPath = if ($HomePath) { Join-Path $env:USERPROFILE $HomePath } else { $null }
    if ($Executable) {
        Write-Host ($Name.PadRight(18) + ' detected (CLI: ' + $Executable.Source + ')')
    } elseif ($ConfigPath -and (Test-Path -LiteralPath $ConfigPath)) {
        Write-Host ($Name.PadRight(18) + ' detected (configuration: ' + $ConfigPath + ')')
    } elseif ($Cloud) {
        Write-Host ($Name.PadRight(18) + ' cloud-capable (local CLI not required)')
    } else {
        Write-Host ($Name.PadRight(18) + ' not detected locally')
    }
}

function Assert-PluginInstaller {
    param([string]$Target)
    switch ($Target) {
        'codex' {
            if (-not (Get-Command codex -ErrorAction SilentlyContinue)) { throw 'Cannot install Codex plugin: codex CLI is not available.' }
            & codex plugin marketplace add --help *> $null
            if ($LASTEXITCODE -ne 0) { throw 'Cannot install Codex plugin: this CLI build or account does not expose marketplace installation.' }
            & codex plugin add --help *> $null
            if ($LASTEXITCODE -ne 0) { throw 'Cannot install Codex plugin: this CLI build or account does not expose plugin installation.' }
        }
        'claude' {
            if (-not (Get-Command claude -ErrorAction SilentlyContinue)) { throw 'Cannot install Claude plugin: claude CLI is not available.' }
            & claude plugin marketplace add --help *> $null
            if ($LASTEXITCODE -ne 0) { throw 'Cannot install Claude plugin: this CLI build or account does not expose marketplace installation.' }
            & claude plugin install --help *> $null
            if ($LASTEXITCODE -ne 0) { throw 'Cannot install Claude plugin: this CLI build or account does not expose plugin installation.' }
        }
        default { throw "No command-line installer is available for: $Target" }
    }
}

function Install-CodexPlugin {
    $RawMarketplaces = & codex plugin marketplace list --json | Out-String
    if ($LASTEXITCODE -ne 0) { throw 'Unable to read Codex marketplaces.' }
    $Marketplaces = $RawMarketplaces | ConvertFrom-Json
    if ($Marketplaces.marketplaces.name -contains $Marketplace) {
        Write-Host "Codex marketplace $Marketplace is already configured."
    } else {
        & codex plugin marketplace add $Repository --ref main --json
        if ($LASTEXITCODE -ne 0) { throw 'Unable to add the Shiori Codex marketplace.' }
    }
    $RawPlugins = & codex plugin list --json | Out-String
    if ($LASTEXITCODE -ne 0) { throw 'Unable to read installed Codex plugins.' }
    $Plugins = $RawPlugins | ConvertFrom-Json
    if ($Plugins.installed.id -contains "shiori@$Marketplace") {
        Write-Host "Codex plugin shiori@$Marketplace is already installed."
    } else {
        & codex plugin add "shiori@$Marketplace" --json
        if ($LASTEXITCODE -ne 0) { throw 'Unable to install the Shiori Codex plugin.' }
    }
}

function Install-ClaudePlugin {
    $RawMarketplaces = & claude plugin marketplace list --json | Out-String
    if ($LASTEXITCODE -ne 0) { throw 'Unable to read Claude marketplaces.' }
    $Marketplaces = $RawMarketplaces | ConvertFrom-Json
    if ($Marketplaces.name -contains $Marketplace) {
        Write-Host "Claude marketplace $Marketplace is already configured."
    } else {
        & claude plugin marketplace add $Repository
        if ($LASTEXITCODE -ne 0) { throw 'Unable to add the Shiori Claude marketplace.' }
    }
    $RawPlugins = & claude plugin list --json | Out-String
    if ($LASTEXITCODE -ne 0) { throw 'Unable to read installed Claude plugins.' }
    $Plugins = $RawPlugins | ConvertFrom-Json
    if ($Plugins.id -contains "shiori@$Marketplace") {
        Write-Host "Claude plugin shiori@$Marketplace is already installed."
    } else {
        & claude plugin install --scope user --yes "shiori@$Marketplace"
        if ($LASTEXITCODE -ne 0) { throw 'Unable to install the Shiori Claude plugin.' }
    }
}

Write-Host 'Shiori agent doctor'
Write-Host "Repository: $Repository"
Write-Host "Mode: $Mode ($ProjectHint)"
Write-Host ''
Show-AgentStatus 'OpenCode' opencode '.config\opencode'
Show-AgentStatus 'Codex' codex '.codex'
Show-AgentStatus 'Claude Code' claude '.claude'
Show-AgentStatus 'ZCode' zcode '.zcode'
Show-AgentStatus 'Cursor' cursor '.cursor'
Show-AgentStatus 'MCode / MiniMax' mcode '.minimax'
Show-AgentStatus 'Windsurf' windsurf '.windsurf'
Show-AgentStatus 'Vibe' vibe '.vibe'
Show-AgentStatus 'Devin' devin '.devin' -Cloud

Write-Host @"

Recommended native setup
  OpenCode: in a checkout it reads .agents/skills automatically. For global use, point opencode.json at a Shiori skills checkout or link it under ~/.config/opencode/skills.
  Codex:    codex plugin marketplace add $Repository ; then open /plugins and install Shiori.
  Claude:   /plugin marketplace add $Repository ; then /plugin install shiori@$Marketplace.
  ZCode:    Settings -> Plugins -> Create -> Add marketplace -> $Repository; install Shiori.
  Cursor:   Settings -> Plugins; add https://github.com/$Repository; install Shiori.
  MCode:    in a checkout it reads .agents/skills automatically. For plugin install, inspect mcode plugin marketplace list --json and place plugins/shiori in its local marketplace.
  Devin:    connect this repository to the cloud workspace; no local executable is required.

Full instructions: $GuideUrl
"@

if ($env:SHIORI_INSTALL) { $Install += $env:SHIORI_INSTALL -split '[, ]+' }
$Install = @($Install | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ } | ForEach-Object { if ($_ -eq 'claude-code') { 'claude' } else { $_ } } | Select-Object -Unique)
if ($Install.Count -gt 0) {
    foreach ($Target in $Install) { Assert-PluginInstaller $Target }
    Write-Host ''
    Write-Host 'Selected installations'
    foreach ($Target in $Install) {
        switch ($Target) {
            'codex' { Install-CodexPlugin }
            'claude' { Install-ClaudePlugin }
        }
    }
}
