# Generated by Shiori. Run from the shiori-brain repository root.
[CmdletBinding()]
param()

$Repository = if ($env:SHIORI_REPOSITORY) { $env:SHIORI_REPOSITORY } else { 'Dragonshorn-Studios/shiori-brain' }

function Show-AgentStatus {
    param([string]$Name, [string]$Command, [string]$HomePath, [switch]$Cloud)
    $Executable = Get-Command $Command -ErrorAction SilentlyContinue
    $ConfigPath = if ($HomePath) { Join-Path $env:USERPROFILE $HomePath } else { $null }
    if ($Executable) {
        Write-Host ($Name.PadRight(18) + ' detected (CLI: ' + $Executable.Source + ')')
    } elseif ($ConfigPath -and (Test-Path -LiteralPath $ConfigPath)) {
        Write-Host ($Name.PadRight(18) + ' detected (configuration: ' + $ConfigPath + ')')
    } elseif ($Cloud) {
        Write-Host ($Name.PadRight(18) + ' cloud-capable (local CLI not required)')
    } else {
        Write-Host ($Name.PadRight(18) + ' not detected locally')
    }
}

Write-Host 'Shiori agent doctor'
Write-Host "Repository: $Repository"
Write-Host ''
Show-AgentStatus 'OpenCode' opencode '.config\opencode'
Show-AgentStatus 'Codex' codex '.codex'
Show-AgentStatus 'Claude Code' claude '.claude'
Show-AgentStatus 'ZCode' zcode '.zcode'
Show-AgentStatus 'Cursor' cursor '.cursor'
Show-AgentStatus 'MCode / MiniMax' mcode '.minimax'
Show-AgentStatus 'Windsurf' windsurf '.windsurf'
Show-AgentStatus 'Vibe' vibe '.vibe'
Show-AgentStatus 'Devin' devin '.devin' -Cloud

Write-Host @"

Recommended native setup
  OpenCode: project skills are ready in .agents/skills. For global use, add this checkout's skills directory to opencode.json or link it under ~/.config/opencode/skills.
  Codex:    codex plugin marketplace add $Repository ; then open /plugins and install Shiori.
  Claude:   /plugin marketplace add $Repository ; then /plugin install shiori@dragonshorn-brain.
  ZCode:    Settings -> Plugins -> Create -> Add marketplace -> $Repository; install Shiori.
  Cursor:   Settings -> Plugins; add https://github.com/$Repository; install Shiori.
  MCode:    project skills are ready in .agents/skills. For plugin install, inspect mcode plugin marketplace list --json and copy plugins/shiori into its local marketplace.
  Devin:    connect this repository to the cloud workspace; no local executable is required.

Full instructions: AGENT-SETUP.md
"@
